"""receieved error, trying to add relationships

Revision ID: 16baf7a3016a
Revises: e96494afe789
Create Date: 2023-06-15 12:01:15.912760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16baf7a3016a'
down_revision = 'e96494afe789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('server_ip', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('world_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servers', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'servers', 'worlds', ['world_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'world_id')
    op.drop_column('servers', 'player_id')
    op.drop_column('servers', 'server_ip')
    # ### end Alembic commands ###
